[package]
name = "messenger-desktop"
version = "1.0.8"
description = "Fast, lightweight Facebook Messenger Desktop application with native notifications."
authors = ["localghost"]
edition = "2021"

[lib]
name = "messenger_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "messenger-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable", "tray-icon", "image-ico", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
